### ISSUE TITLE
Issues with NY data

### ISSUE THREAD

**Issue by TruffleClock** [COVID19Tracking/covid-tracking-data#8]
Hello, wanted to report 2 issues related to NY data:

1) Hospitalizations and deaths for NY on 3/23 are the same as for 3/22, looks like it did not update

2) I'm getting an empty array from https://covidtracking.com/api/states/daily?state=NY

**Comment by julia326** [comment]
Hi there - thanks for the report! Our team fixed this shortly after publishing today's data, sorry for the error.

**Comment by TruffleClock** [comment]
@julia326 Thanks for the quick update! However, the number of deaths for NY is still the same as yesterday. Has the state just not reported new numbers for today? Or is there a data issue?

**Comment by julia326** [comment]
Apologies! This repo is actually a regularly scheduled backup of our live data, and I hadn't run the backup before responding to your message - my bad. Should be fixed in this repo now.

**Comment by TruffleClock** [comment]
@julia326 I actually wasn't using this repo - I'm looking at https://covidtracking.com/api/states/daily?state=NY

114 deaths for today 3/23 is the same as yesterday 3/22. Also shows 114 in the spreadsheet for current. Did NY state just not give an update today?

**Comment by TruffleClock** [comment]
@julia326 Just wanted to follow up here - I am still seeing 114 for deaths in NY for both 3/22 and 3/23. Today (3/24) was updated correctly. Is it possible to update the data for 3/23?
